In [1]:
# feature_engineering_exercises

### 1. Load the tips dataset.

- a. Create a column named tip_percentage. This should be the tip amount divided by the total bill.
- b. Create a column named price_per_person. This should be the total bill divided by the party size.
- c. Before using any of the methods discussed in the lesson, which features do you think would be most important for predicting the tip amount? The tip percentage?
- d. Use select k best and recursive feature elimination to select the top 2 features for predicting tip amount. What are they?
- e. Use select k best and recursive feature elimination to select the top 2 features for predicting tip percentage. What are they?
- f. Why do you think select k best and recursive feature elimination might give different answers for the top features? Does this change as you change the number of features your are selecting?

### 2. Write a function named select_kbest that takes in the predictors (X), the target (y), and the number of features to select (k) and returns the names of the top k selected features based on the SelectKBest class. Test your function with the tips dataset. You should see the same results as when you did the process manually.

### 3. Write a function named rfe that takes in the predictors, the target, and the number of features to select. It should return the top k features based on the RFE class. Test your function with the tips dataset. You should see the same results as when you did the process manually.

### 4. Load the swiss dataset and use all the other features to predict Fertility. Find the top 3 features using both select k best and recursive feature elimination (use the functions you just built to help you out).

In [60]:
# imports
import pandas as pd
import numpy as np
import pydataset

from sklearn.model_selection import train_test_split
import sklearn.linear_model
import sklearn.feature_selection
import sklearn.preprocessing

In [61]:
# 1. Load the 'tips' dataset
tips = pydataset.data('tips')

tips['smoker'] = (tips.smoker == 'Yes').astype(int)
tips['dinner'] = (tips.time == 'Dinner').astype(int)

tips.head() # check_yo_head

total_bill   tip     sex  smoker  day    time  size  dinner
1       16.99  1.01  Female       0  Sun  Dinner     2       1
2       10.34  1.66    Male       0  Sun  Dinner     3       1
3       21.01  3.50    Male       0  Sun  Dinner     3       1
4       23.68  3.31    Male       0  Sun  Dinner     2       1
5       24.59  3.61  Female       0  Sun  Dinner     4       1

In [62]:
tips.shape

(244, 8)

In [63]:
# a. Create a column named tip_percentage. This should be the tip amount divided by the total bill.
tips['tip_percentage'] = tips.tip / tips.total_bill 
tips.head() # check_yo_head

total_bill   tip     sex  smoker  day    time  size  dinner  tip_percentage
1       16.99  1.01  Female       0  Sun  Dinner     2       1        0.059447
2       10.34  1.66    Male       0  Sun  Dinner     3       1        0.160542
3       21.01  3.50    Male       0  Sun  Dinner     3       1        0.166587
4       23.68  3.31    Male       0  Sun  Dinner     2       1        0.139780
5       24.59  3.61  Female       0  Sun  Dinner     4       1        0.146808

In [64]:
# b. Create a column named price_per_person. This should be the total bill divided by the party size.
tips['price_per_person'] = tips.total_bill / tips['size'] # .size is and function and I need to use [' '] or rename the column
tips.head() # check_yo_head

total_bill   tip     sex  smoker  day    time  size  dinner  \
1       16.99  1.01  Female       0  Sun  Dinner     2       1   
2       10.34  1.66    Male       0  Sun  Dinner     3       1   
3       21.01  3.50    Male       0  Sun  Dinner     3       1   
4       23.68  3.31    Male       0  Sun  Dinner     2       1   
5       24.59  3.61  Female       0  Sun  Dinner     4       1   

   tip_percentage  price_per_person  
1        0.059447          8.495000  
2        0.160542          3.446667  
3        0.166587          7.003333  
4        0.139780         11.840000  
5        0.146808          6.147500

In [65]:
# c. Before using any of the methods discussed in the lesson, which features do you think would be most important for predicting the tip amount? The tip percentage?
# total_bill and time
# total_bill and size

In [66]:
# d. Use select k best and recursive feature elimination to select the top 2 features for predicting tip amount. What are they?

X = tips[['total_bill', 'size', 'smoker', 'dinner']]
y = tips.tip

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.85, random_state=123)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [67]:
kbest = SelectKBest(f_regression, k=2)
kbest.fit(X_train_scaled, y_train)

SelectKBest(k=2, score_func=<function f_regression at 0x7fd718458dc0>)

In [68]:
kbest.get_support()

array([ True,  True, False, False])

In [69]:
X_train.columns[kbest.get_support()]

Index(['total_bill', 'size'], dtype='object')

In [70]:
X_kbest = kbest.transform(X_train_scaled)
X_kbest.shape

(36, 2)

In [71]:
rfe = RFE(estimator=LinearRegression(), n_features_to_select=2)
rfe.fit(X_train_scaled, y_train)
rfe.get_support()

array([ True, False,  True, False])

In [72]:
rfe.ranking_

array([1, 2, 1, 3])

In [73]:
X_train.columns[rfe.get_support()]

Index(['total_bill', 'smoker'], dtype='object')

In [74]:
pd.Series(rfe.ranking_, index=X_train.columns)

total_bill    1
size          2
smoker        1
dinner        3
dtype: int64

In [75]:
# e. Use select k best and recursive feature elimination to select the top 2 features for predicting tip percentage. What are they?

X = tips[['total_bill', 'size', 'smoker', 'dinner']]
y = tips.tip_percentage

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.85, random_state=123)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [76]:
kbest = SelectKBest(f_regression, k=2)
kbest.fit(X_train_scaled, y_train)

SelectKBest(k=2, score_func=<function f_regression at 0x7fd718458dc0>)

In [77]:
kbest.get_support()

array([ True, False,  True, False])

In [78]:
X_train.columns[kbest.get_support()]

Index(['total_bill', 'smoker'], dtype='object')

In [79]:
X_kbest = kbest.transform(X_train_scaled)
X_kbest.shape

(36, 2)

In [80]:
rfe = RFE(estimator=LinearRegression(), n_features_to_select=2)
rfe.fit(X_train_scaled, y_train)
rfe.get_support()

array([ True, False,  True, False])

In [81]:
rfe.ranking_

array([1, 2, 1, 3])

In [82]:
X_train.columns[rfe.get_support()]

Index(['total_bill', 'smoker'], dtype='object')

In [83]:
pd.Series(rfe.ranking_, index=X_train.columns)

total_bill    1
size          2
smoker        1
dinner        3
dtype: int64

In [84]:
# f. Why do you think select k best and recursive feature elimination might give different answers for the top features? 
# Does this change as you change the number of features your are selecting?



In [85]:
def split(df, stratify_by=""):
    '''
    take in a DataFrame and return train, validate, and test DataFrames.
    return train, validate, test DataFrames.
    '''
    train_validate, test = train_test_split(df, test_size=.2, random_state=123)
    train, validate = train_test_split(train_validate, 
                                       test_size=.3, 
                                       random_state=123)
    return train, validate, test

In [86]:

target = "tip"

# split train into X (dataframe, drop target) & y (series, keep target only)
X_train = train.drop(columns=[target, 'tip_percentage'])
y_train = train[target]

# split validate into X (dataframe, drop target) & y (series, keep target only)
X_validate = validate.drop(columns=[target, 'tip_percentage'])
y_validate = validate[target]

# split test into X (dataframe, drop target) & y (series, keep target only)
X_test = test.drop(columns=[target, 'tip_percentage'])
y_test = test[target]

X_train.head()

NameError: name 'train' is not defined

In [87]:
# 2. Write a function named select_kbest that takes in the predictors (X), the target (y), and the number of features to select (k) and returns the names of the top k selected features based on the SelectKBest class. 
# Test your function with the tips dataset. 
# You should see the same results as when you did the process manually.

def select_kbest(X, y, k):
    # make the object
    kbest = sklearn.feature_selection.SelectKBest(
        sklearn.feature_selection.f_regression,
        k=k)

    # fit the object
    kbest.fit(X, y)
    
    # use the object (.get_support() is that array of booleans to filter the list of column names)
    return X.columns[kbest.get_support()].tolist()

kbest_feats = select_kbest(X_train, y_train, 2)


In [88]:

kbest_feats

['total_bill', 'smoker']

In [89]:
def show_features_rankings(X_train, rfe):
    """
    Takes in a dataframe and a fit RFE object in order to output the rank of all features
    """
    # rfe here is reference rfe from cell 15
    var_ranks = rfe.ranking_
    var_names = X_train.columns.tolist()
    ranks = pd.DataFrame({'Var': var_names, 'Rank': var_ranks})
    ranks = ranks.sort_values(by="Rank", ascending=True)
    return ranks

In [90]:
# Exercise 3
# Write a function named rfe that takes in the predictors, the target, and the number of features to select. It should return the top k features based on the RFE class. Test your function with the tips dataset. You should see the same results as when you did the process manually.

def select_rfe(X, y, k):
    # make the thing
    lm = sklearn.linear_model.LinearRegression()
    rfe = sklearn.feature_selection.RFE(lm, n_features_to_select=k)

    # Fit the thing
    rfe.fit(X, y)
    
    # use the thing
    features_to_use = X.columns[rfe.support_].tolist()
    
    # we need to send show_feature_rankings a trained/fit RFE object
    all_rankings = show_features_rankings(X, rfe)
    
    return features_to_use, all_rankings

In [91]:

# (Bonus)
# Use RFE to produce a dataframe of the ranked features

# rfe here is reference rfe from cell 15
var_ranks = rfe.ranking_
var_names = X_train.columns.tolist()
ranks = pd.DataFrame({'Var': var_names, 'Rank': var_ranks})
ranks.sort_values(by="Rank", ascending=True)

Var  Rank
0  total_bill     1
2      smoker     1
1        size     2
3      dinner     3

In [93]:

# Exercise 4
# Load the swiss dataset and use all the other features to predict Fertility. Find the top 3 features using both select k best and recursive feature elimination (use the functions you just built to help you out).

swiss = pydataset.data('swiss')
swiss.head()

Fertility  Agriculture  Examination  Education  Catholic  \
Courtelary         80.2         17.0           15         12      9.96   
Delemont           83.1         45.1            6          9     84.84   
Franches-Mnt       92.5         39.7            5          5     93.40   
Moutier            85.8         36.5           12          7     33.77   
Neuveville         76.9         43.5           17         15      5.16   

              Infant.Mortality  
Courtelary                22.2  
Delemont                  22.2  
Franches-Mnt              20.2  
Moutier                   20.3  
Neuveville                20.6

In [94]:

# Split the data
train, validate, test = split(swiss, stratify_by="Fertility")

# Setup X and y
X_train = train.drop(columns='Fertility')
y_train = train.Fertility

X_validate = validate.drop(columns='Fertility')
y_validate = validate.Fertility

X_test = test.drop(columns='Fertility')
y_test = test.Fertility

In [95]:
# Scale the data
scaler = sklearn.preprocessing.MinMaxScaler()

# Fit the scaler
scaler.fit(X_train)

# Use the scaler to transform train, validate, test
X_train_scaled = scaler.transform(X_train)
X_validate_scaled = scaler.transform(X_validate)
X_test_scaled = scaler.transform(X_test)


# Turn everything into a dataframe
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_validate_scaled = pd.DataFrame(X_validate_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_train.columns)

In [96]:

# Find the top 3 features using kbest
select_kbest(X_train_scaled, y_train, 3)

['Examination', 'Catholic', 'Infant.Mortality']

In [97]:
# Find the top 3 features using RFE
selected_features, all_rankings = select_rfe(X_train, y_train, 3)
print(selected_features)
all_rankings

['Agriculture', 'Examination', 'Infant.Mortality']


Var  Rank
0       Agriculture     1
1       Examination     1
4  Infant.Mortality     1
2         Education     2
3          Catholic     3