In [1]:
# feature_engineering_exercises

### 1. Load the tips dataset.

- a. Create a column named tip_percentage. This should be the tip amount divided by the total bill.
- b. Create a column named price_per_person. This should be the total bill divided by the party size.
- c. Before using any of the methods discussed in the lesson, which features do you think would be most important for predicting the tip amount? The tip percentage?
- d. Use select k best and recursive feature elimination to select the top 2 features for predicting tip amount. What are they?
- e. Use select k best and recursive feature elimination to select the top 2 features for predicting tip percentage. What are they?
- f. Why do you think select k best and recursive feature elimination might give different answers for the top features? Does this change as you change the number of features your are selecting?

### 2. Write a function named select_kbest that takes in the predictors (X), the target (y), and the number of features to select (k) and returns the names of the top k selected features based on the SelectKBest class. Test your function with the tips dataset. You should see the same results as when you did the process manually.

### 3. Write a function named rfe that takes in the predictors, the target, and the number of features to select. It should return the top k features based on the RFE class. Test your function with the tips dataset. You should see the same results as when you did the process manually.

### 4. Load the swiss dataset and use all the other features to predict Fertility. Find the top 3 features using both select k best and recursive feature elimination (use the functions you just built to help you out).

In [26]:
# imports
import pandas as pd
import numpy as np
import pydataset

from sklearn.feature_selection import SelectKBest, f_regression, RFE
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [27]:
# 1. Load the 'tips' dataset
tips = pydataset.data('tips')

tips['smoker'] = (tips.smoker == 'Yes').astype(int)
tips['dinner'] = (tips.time == 'Dinner').astype(int)

tips.head() # check_yo_head

total_bill   tip     sex  smoker  day    time  size  dinner
1       16.99  1.01  Female       0  Sun  Dinner     2       1
2       10.34  1.66    Male       0  Sun  Dinner     3       1
3       21.01  3.50    Male       0  Sun  Dinner     3       1
4       23.68  3.31    Male       0  Sun  Dinner     2       1
5       24.59  3.61  Female       0  Sun  Dinner     4       1

In [29]:
tips.shape

(244, 8)

In [4]:
# a. Create a column named tip_percentage. This should be the tip amount divided by the total bill.
tips['tip_percentage'] = tips.tip / tips.total_bill 
tips.head() # check_yo_head

total_bill   tip     sex  smoker  day    time  size  dinner  tip_percentage
1       16.99  1.01  Female       0  Sun  Dinner     2       1        0.059447
2       10.34  1.66    Male       0  Sun  Dinner     3       1        0.160542
3       21.01  3.50    Male       0  Sun  Dinner     3       1        0.166587
4       23.68  3.31    Male       0  Sun  Dinner     2       1        0.139780
5       24.59  3.61  Female       0  Sun  Dinner     4       1        0.146808

In [5]:
# b. Create a column named price_per_person. This should be the total bill divided by the party size.
tips['price_per_person'] = tips.total_bill / tips['size'] # .size is and function and I need to use [' '] or rename the column
tips.head() # check_yo_head

total_bill   tip     sex  smoker  day    time  size  dinner  \
1       16.99  1.01  Female       0  Sun  Dinner     2       1   
2       10.34  1.66    Male       0  Sun  Dinner     3       1   
3       21.01  3.50    Male       0  Sun  Dinner     3       1   
4       23.68  3.31    Male       0  Sun  Dinner     2       1   
5       24.59  3.61  Female       0  Sun  Dinner     4       1   

   tip_percentage  price_per_person  
1        0.059447          8.495000  
2        0.160542          3.446667  
3        0.166587          7.003333  
4        0.139780         11.840000  
5        0.146808          6.147500

In [6]:
# c. Before using any of the methods discussed in the lesson, which features do you think would be most important for predicting the tip amount? The tip percentage?
# total_bill and time
# total_bill and size

In [7]:
# d. Use select k best and recursive feature elimination to select the top 2 features for predicting tip amount. What are they?

X = tips[['total_bill', 'size', 'smoker', 'dinner']]
y = tips.tip

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.85, random_state=123)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
kbest = SelectKBest(f_regression, k=2)
kbest.fit(X_train_scaled, y_train)

SelectKBest(k=2, score_func=<function f_regression at 0x7fbd728b40d0>)

In [9]:
kbest.get_support()

array([ True,  True, False, False])

In [10]:
X_train.columns[kbest.get_support()]

Index(['total_bill', 'size'], dtype='object')

In [11]:
X_kbest = kbest.transform(X_train_scaled)
X_kbest.shape

(36, 2)

In [12]:
rfe = RFE(estimator=LinearRegression(), n_features_to_select=2)
rfe.fit(X_train_scaled, y_train)
rfe.get_support()

array([ True, False,  True, False])

In [13]:
rfe.ranking_

array([1, 2, 1, 3])

In [14]:
X_train.columns[rfe.get_support()]

Index(['total_bill', 'smoker'], dtype='object')

In [15]:
pd.Series(rfe.ranking_, index=X_train.columns)

total_bill    1
size          2
smoker        1
dinner        3
dtype: int64

In [16]:
# e. Use select k best and recursive feature elimination to select the top 2 features for predicting tip percentage. What are they?

X = tips[['total_bill', 'size', 'smoker', 'dinner']]
y = tips.tip_percentage

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.85, random_state=123)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
kbest = SelectKBest(f_regression, k=2)
kbest.fit(X_train_scaled, y_train)

SelectKBest(k=2, score_func=<function f_regression at 0x7fbd728b40d0>)

In [18]:
kbest.get_support()

array([ True, False,  True, False])

In [19]:
X_train.columns[kbest.get_support()]

Index(['total_bill', 'smoker'], dtype='object')

In [20]:
X_kbest = kbest.transform(X_train_scaled)
X_kbest.shape

(36, 2)

In [21]:
rfe = RFE(estimator=LinearRegression(), n_features_to_select=2)
rfe.fit(X_train_scaled, y_train)
rfe.get_support()

array([ True, False,  True, False])

In [22]:
rfe.ranking_

array([1, 2, 1, 3])

In [23]:
X_train.columns[rfe.get_support()]

Index(['total_bill', 'smoker'], dtype='object')

In [24]:
pd.Series(rfe.ranking_, index=X_train.columns)

total_bill    1
size          2
smoker        1
dinner        3
dtype: int64

In [25]:
# f. Why do you think select k best and recursive feature elimination might give different answers for the top features? 
# Does this change as you change the number of features your are selecting?



In [ ]:
# 2. Write a function named select_kbest that takes in the predictors (X), the target (y), and the number of features to select (k) and returns the names of the top k selected features based on the SelectKBest class. 
# Test your function with the tips dataset. 
# You should see the same results as when you did the process manually.

def select_kbest():
    